[package]
name = "sdb"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
iced-x86 = "1.21.0"
libc = "0.2.172"
nix = { version = "0.30.1", features = ["process", "uio", "fs", "personality", "ptrace"] }
rustyline = "15.0.0"
